CREATE TABLE [dbo].[Reserva] (
    [idReserva]             INT NOT NULL,
    [idDetalleReserva]      INT NULL,
    [idCliente]             INT NULL,
    [idEmpleado]            INT NULL,
    [idTipoDocumento]       INT  NULL,
    [numeroDocumento]       NVARCHAR (8) NULL,
    [idDocumentoViaje]      INT  NULL,
    [numeroReserva]         INT NULL,
    [monto]                 INT NULL,
    [fechaReserva]          DATE         NULL,
    [idSeguroViajero]       INT NULL,
    [idServicioAlojamiento] INT NULL,
    [idServicioTraslado]    INT NULL,
    [comprada]              BIT          NULL,
    [efectuada]             BIT          NULL,
    CONSTRAINT [PK_Reserva] PRIMARY KEY CLUSTERED ([idReserva] ASC),
    CONSTRAINT [FK_Reserva_Cliente] FOREIGN KEY ([idCliente]) REFERENCES [dbo].[Cliente] ([idCliente]),
    CONSTRAINT [FK_Reserva_Empleado] FOREIGN KEY ([idEmpleado]) REFERENCES [dbo].[Empleado] ([idEmpleado]),
    CONSTRAINT [FK_Reserva_ReservaDetalle] FOREIGN KEY ([idDetalleReserva]) REFERENCES [dbo].[ReservaDetalle] ([idDetallaReserva]),
    CONSTRAINT [FK_Reserva_SeguroViajero] FOREIGN KEY ([idSeguroViajero]) REFERENCES [dbo].[SeguroViajero] ([idSeguroViajero]),
    CONSTRAINT [FK_Reserva_ServicioAlojamiento] FOREIGN KEY ([idServicioAlojamiento]) REFERENCES [dbo].[ServicioAlojamiento] ([idServicioAlojamiento]),
    CONSTRAINT [FK_Reserva_ServicioTraslado] FOREIGN KEY ([idServicioTraslado]) REFERENCES [dbo].[ServicioTraslado] ([idServicioTraslado]),
    CONSTRAINT [FK_Reserva_TipoDocumento1] FOREIGN KEY ([idTipoDocumento]) REFERENCES [dbo].[TipoDocumento] ([idTipoDocumento])
);

